#include "MWDBoneNode.h"
namespace MWDEngine {
	INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDBoneNode)
	ADD_PRIORITY(MWDNode)
	ADD_INITIAL_FUNCTION(InitialClassFactory)
	INITIAL_WITH_INIT_TERMINAL_END(MWDBoneNode)

	BEGIN_ADD_PROPERTY(MWDBoneNode)
	END_ADD_PROPERTY
}