#include "MWDDataBuffer.h"
namespace MWDEngine {
	INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDDataBuffer)
    ADD_PRIORITY(MWDObject)
    INITIAL_WITH_INIT_TERMINAL_END(MWDDataBuffer)

    BEGIN_ADD_PROPERTY(MWDDataBuffer)
    END_ADD_PROPERTY

}