#include "MWDIndexBuffer.h"
namespace MWDEngine {
	INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDIndexBuffer)
    ADD_PRIORITY(MWDBind)
    ADD_INITIAL_FUNCTION(InitialClassFactory)
    INITIAL_WITH_INIT_TERMINAL_END(MWDIndexBuffer)

    BEGIN_ADD_PROPERTY(MWDIndexBuffer)
    END_ADD_PROPERTY

}