#include "MWDMeshData.h"
namespace MWDEngine {
	INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDMeshData)
	ADD_PRIORITY(MWDObject)
	INITIAL_WITH_INIT_TERMINAL_END(MWDMeshData)

	BEGIN_ADD_PROPERTY(MWDMeshData)
	END_ADD_PROPERTY
}