#include "MWDTexture.h"
namespace MWDEngine {
	INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDTexture)
    ADD_PRIORITY(MWDObject)
    INITIAL_WITH_INIT_TERMINAL_END(MWDTexture)

    BEGIN_ADD_PROPERTY(MWDTexture)
    END_ADD_PROPERTY



    INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDTexture2D)
    ADD_PRIORITY(MWDTexture)
    INITIAL_WITH_INIT_TERMINAL_END(MWDTexture2D)

    BEGIN_ADD_PROPERTY(MWDTexture2D)
    END_ADD_PROPERTY



    INITIAL_WITH_INIT_TERMINAL_BEGIN(MWDTextureCubic)
    ADD_PRIORITY(MWDTexture)
    INITIAL_WITH_INIT_TERMINAL_END(MWDTextureCubic)

    BEGIN_ADD_PROPERTY(MWDTextureCubic)
    END_ADD_PROPERTY
}